### ISSUE TITLE
Inquiry about 6DOF pose label accuracy

### ISSUE THREAD

**Issue by happyCodingSusan** [TRI-ML/sdflabel#2]
@zakharos, @wadimkehl , @arjunbhargava , @AdrienGaidon-TRI ,

Thank you for sharing your amazing work!

Besides labeling 3D cuboid, I think your method can label 6DOF pose as well since the surface points are transformed based on the pose and scale, right? Do you have any number about 6DOF pose label accuracy?

**Comment by zakharos** [comment]
Thank you for your interest in our work!

Yes, we regress both the scaled object shape and the 6DoF pose used to place the object in the scene. In particular, the [PoseEstimator](https://github.com/TRI-ML/sdflabel/blob/master/utils/pose.py) class is responsible for computing the pose. In the [paper](https://arxiv.org/pdf/1911.11288.pdf) we only use the metrics based on IoU (BEV IoU and 3D IoU from KITTI3D) as well as the distance-thresholded metric (NS) from NuScenes. However, one could also easily plug in any other desired metric, e.g. ADD.
