### ISSUE TITLE
Test process

### ISSUE THREAD

**Issue by MaitaYuki** [TRI-ML/sdflabel#5]
Great work, thanks for sharing!

What are the correct evaluation steps? 
I suppose "python main.py configs/config_train.ini --train" is for generating models.
What are supposed to output by the following commands?
python main.py configs/config_refine.ini --demo
python main.py configs/config_refine.ini --refine

**Comment by zakharos** [comment]
Hi MaitaYuki,

Thank you for your question! 

- `python main.py configs/config_train.ini --train` is used for training the CSS network that outputs correspondences and latent shape codes;
- `python main.py configs/config_refine.ini --demo` shows an example of the optimization process on a single KITTI frame. Optimization is done for both object's shape and pose.
- `python main.py configs/config_refine.ini --refine` does the refinement on the whole KITTI dataset.

Please also take a look at the readme file. It gives more details about the respective commands.
